#Experience API Configuration

http.port: "8083"

http_Listener:
  listen_path: "/eapi"
  
http_Requestor:
  request_host_papi: "pAPI-placeOrder-dockercon.us-e2.cloudhub.io"
  request_path_papi: "/papi"
  #request_basepath_SOR_inventory: "/api"
  request_port_papi: "80"
