#System API Configuration

http_Listener:
  listen_path: "/sapi"
  
http_Requestor:
  request_host_SOR_inventory: "llb.sixeyed.com"
  request_path_SOR_inventory: "/products"
#  request_basepath_SOR_inventory: "/api"
  request_port_SOR_inventory: "9080"
