#System API Configuration

http_Listener:
  listen_path: "/sapi"
  
http_Requestor:
  request_host_SOR_inventory: "sor-product.us-e2.cloudhub.io"
  request_path_SOR_inventory: "/products"
  request_basepath_SOR_inventory: "/api"
  request_port_SOR_inventory: "80"
